/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "musique"
include(":musique-core")
include(":alacdecoder",":jaad",":cuelib",":jaudiotagger",":javaFlacEncoder",
    ":jflac",":tta",":vorbis-java",":wavpack",":jmac",":javalayer",":jorbis",":last.fm-bindings",":discogs")

project(":alacdecoder").projectDir = file("dependencies/alacdecoder")
project(":jaad").projectDir = file("dependencies/jaad")
project(":cuelib").projectDir = file("dependencies/cuelib")
project(":jaudiotagger").projectDir = file("dependencies/jaudiotagger")
project(":javaFlacEncoder").projectDir = file("dependencies/javaFlacEncoder")
project(":jflac").projectDir = file("dependencies/jflac")
project(":tta").projectDir = file("dependencies/tta")
project(":vorbis-java").projectDir = file("dependencies/vorbis-java")
project(":wavpack").projectDir = file("dependencies/wavpack")
project(":jmac").projectDir = file("dependencies/jmac")
project(":javalayer").projectDir = file("dependencies/javalayer")
project(":jorbis").projectDir = file("dependencies/jorbis")
project(":last.fm-bindings").projectDir = file("dependencies/last.fm-bindings")
project(":discogs").projectDir = file("dependencies/discogs")

include(":musique-player")
