/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.tulskiy.java-conventions")
    id("java")
}

dependencies {
    implementation(project(":musique-player"))
    implementation(project(":last.fm-bindings"))
    implementation("com.github.tulskiy:jkeymaster:1.3")
    implementation("commons-configuration:commons-configuration:1.6")
    testImplementation("junit:junit:4.8.1")
}

description = "musique-core"
